##### One Hot Encoding

In [6]:
import tensorflow as tf
A = [1, 0, 0, 1]
A_encoded = tf.one_hot(A, depth=4)
A_encoded

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [7]:
A_encoded2 = tf.one_hot(A, depth=4, on_value="Male", off_value="Female")
A_encoded2

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Female', b'Male', b'Female', b'Female'],
       [b'Male', b'Female', b'Female', b'Female'],
       [b'Male', b'Female', b'Female', b'Female'],
       [b'Female', b'Male', b'Female', b'Female']], dtype=object)>

Trying more Math Func in tensor (Sqaure, root, log)

In [8]:
B = tf.range(1,15)

In [10]:
# Square
tf.square(B)

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196], dtype=int32)>

In [13]:
# Root
tf.sqrt(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166249, 3.4641016,
       3.6055512, 3.7416575], dtype=float32)>

In [15]:
# Log
tf.math.log(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574], dtype=float32)>

In [17]:
# Cummulative Sum
tf.math.cumsum(B)

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105], dtype=int32)>

In [23]:
# Gamma
tf.math.igamma(tf.cast(B, dtype=tf.float32), tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([0.6321205 , 0.5939942 , 0.5768099 , 0.5665299 , 0.5595068 ,
       0.5543207 , 0.5502885 , 0.54703957, 0.544347  , 0.54207104,
       0.54011124, 0.5384028 , 0.53689575, 0.53555304], dtype=float32)>

In [25]:
tf.math.tan(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([ 1.5574077e+00, -2.1850398e+00, -1.4254655e-01,  1.1578213e+00,
       -3.3805151e+00, -2.9100618e-01,  8.7144798e-01, -6.7997112e+00,
       -4.5231566e-01,  6.4836085e-01, -2.2595085e+02, -6.3585991e-01,
        4.6302113e-01,  7.2446065e+00], dtype=float32)>