##### Tensor x NumPy


In [1]:
import tensorflow as tf
import numpy as np

In [12]:
# Create Numpy Through Tensor
A = tf.constant(np.array([3., 4., 5.]))
B = tf.constant([3., 4., 5.,])
A

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [7]:
# Convert Tensor to Numpy
np.array(A), type(np.array(A))

(array([3., 4., 5.]), numpy.ndarray)

In [10]:
# Convert Tensor to Numpy
A.numpy(), type(A.numpy())

(array([3., 4., 5.]), numpy.ndarray)

In [18]:
A.dtype, B.dtype

(tf.float64, tf.float32)

In [20]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]