In [2]:
import tensorflow as tf

##### Creating Different Tensors

In [12]:
string = tf.Variable("Hello Tensorflow", tf.string)
number = tf.Variable(69, tf.int16)
number2 = tf.Variable(3.14, dtype=tf.float64)
number2.dtype

tf.float64

##### Rank on Tensor
Rank: Dimensional of number in tensor

In [4]:
rank1_tensor = tf.Variable(["Hello", "Tensorflow"], tf.string)
rank2_tensor = tf.Variable([[3, 4, 5], [6, 7, 8]], tf.int64)

In [5]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

##### Shape on Tensor

In [6]:
tf.shape(rank1_tensor)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

##### Modify Tensor Shape

In [7]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor1)
print(tensor2)
print(tensor3)
tensor2.ndim

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


3

##### Types of Tensors

- Varibles
- Constant
- Placeholder
- Sparsetensor

##### Types of Dimension

- Scalar = A single number 
- Vector = A nunber with direction (1 dimension)
- Matrix = A 2 dimensional nunbers
- Tensor = an n-dimensional array of numbers (When n can be any number, a n=0 is scalar, a n=1 is vector)

In [24]:
# Craete Scalar

scalar = tf.constant(69, dtype=tf.int32)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=69>

In [25]:
# Create Vector
vector = tf.constant([12, 2], dtype=tf.int32)
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  2], dtype=int32)>

In [17]:
# Custome dtype

matrix = tf.constant([[2.3, 4.5],
                     [3.3, 4.2]], dtype=tf.float32)

matrix.ndim
matrix.dtype

tf.float32

In [23]:
# Create a tensor

tensor = tf.constant([[[4, 3, 5],
                       [2, 5, 7]],
                      [[3, 1, 2],
                       [6, 4, 3]],
                      [[4, 4, 3],
                       [2, 5, 3]]]) 
tensor
tensor.ndim

3

##### Evaluating Tensor

In [8]:
# Example


# with tf.Session() as sess:
#     tensor_name.eval()

Example

In [16]:
t = tf.ones([6,6,6,6])
# print(t)
t2 = tf.reshape(t, [1296]) # Flattening by calculate previous dimension setup
print(t2)

tf.Tensor([1. 1. 1. ... 1. 1. 1.], shape=(1296,), dtype=float32)
