##### TF Constant

In [1]:
import tensorflow as tf

In [2]:
# Craete Scalar

scalar = tf.constant(69, dtype=tf.int32)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=69>

In [3]:
# Create Vector
vector = tf.constant([12, 2], dtype=tf.int32)
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  2], dtype=int32)>

In [4]:
# Custome dtype

matrix = tf.constant([[2.3, 4.5],
                     [3.3, 4.2]], dtype=tf.float32)

matrix.ndim
matrix.dtype

tf.float32

In [5]:
# Create a tensor

tensor = tf.constant([[[4, 3, 5],
                       [2, 5, 7]],
                      [[3, 1, 2],
                       [6, 4, 3]],
                      [[4, 4, 3],
                       [2, 5, 3]]]) 
tensor
tensor.ndim

3

##### What we've created

- Scalar = A single number 
- Vector = A nunber with direction (1 dimension)
- Matrix = A 2 dimensional nunbers
- Tensor = an n-dimensional array of numbers (When n can be any number, a n=0 is scalar, a n=1 is vector)

##### TF Variable

In [6]:
# Create Variable
changeable_tensor = tf.Variable([10, 15])
unchangeable_tensor = tf.constant([12, 17])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 15], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 17], dtype=int32)>)

In [8]:
# Assign variable
changeable_tensor[1].assign(23)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 23], dtype=int32)>