##### Generate Tensor Random Number

In [1]:
import tensorflow as tf

In [2]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=[3, 2])
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=[3, 2])
random_2, random_1, random_2 == random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

##### Shuffle a tensor

In [3]:
not_shuffled = tf.constant([[4, 3, 2],
                            [3, 5, 2],
                            [4, 2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 3, 2],
       [3, 5, 2],
       [4, 2, 5]], dtype=int32)>

In [4]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 3, 2],
       [3, 5, 2],
       [4, 2, 5]], dtype=int32)>

In [5]:
# tf.random.set_seed(42)
shuffled_seed = tf.random.shuffle(not_shuffled, seed=42)
shuffled_seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 2, 5],
       [3, 5, 2],
       [4, 3, 2]], dtype=int32)>

⚒️ Exercise: Create 5 different random with set seed and shuffle

To get our number shuffled in the same order we need to use global seed and operation 

seed with the same values.

In [6]:
matrix = tf.constant([[5, 6, 4],
                      [9, 6, 8],
                      [7, 4, 0]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 6, 4],
       [9, 6, 8],
       [7, 4, 0]], dtype=int32)>

In [7]:
tf.random.set_seed(1234)
set_seed1 = tf.random.shuffle(matrix, seed=1234)
set_seed1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 4, 0],
       [5, 6, 4],
       [9, 6, 8]], dtype=int32)>

In [8]:
tf.random.set_seed(1342)
set_seed2 = tf.random.shuffle(matrix, seed=1342)
set_seed1, set_seed2, set_seed1 == set_seed2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[7, 4, 0],
        [5, 6, 4],
        [9, 6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[7, 4, 0],
        [9, 6, 8],
        [5, 6, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [False,  True, False],
        [False,  True, False]])>)

In [9]:
tf.random.set_seed(69)
set_seed3 = tf.random.shuffle(matrix, seed=69)
set_seed3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 4, 0],
       [5, 6, 4],
       [9, 6, 8]], dtype=int32)>

In [10]:
tf.random.set_seed(96)
set_seed4= tf.random.shuffle(matrix, seed=96)
set_seed4
set_seed3, set_seed4, set_seed4 == set_seed3

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[7, 4, 0],
        [5, 6, 4],
        [9, 6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[9, 6, 8],
        [7, 4, 0],
        [5, 6, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False,  True, False]])>)

In [12]:
tf.random.set_seed(24)
set_seed5 = tf.random.shuffle(not_shuffled, seed=24)
shuffled_seed, set_seed5, shuffled_seed == set_seed5

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 2, 5],
        [3, 5, 2],
        [4, 3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 2, 5],
        [4, 3, 2],
        [3, 5, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [False, False,  True],
        [False, False,  True]])>)

##### Other Way to Create Tensor 

In [18]:
import numpy as np


numpy_a= np.arange(1, 25)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
tensor_a = tf.constant(numpy_a, shape=(4, 2, 3))
tensor_b = tf.constant(numpy_a)
tensor_a, tensor_b

(<tf.Tensor: shape=(4, 2, 3), dtype=int64, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]],
 
        [[19, 20, 21],
         [22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [21]:
tensor_b.ndim, tensor_a.ndim

(1, 3)