##### Getting Information from Tensor

When dealing with tensors you probably want to be aware of the following attributes:
- Shape
- Rank
- Axis or Dimension
- Size

In [16]:
import tensorflow as tf

In [20]:
# Creating rank 4 dimension

rank4_tensor = tf.ones(shape=[2,2,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 2, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [23]:
rank4_tensor.ndim, rank4_tensor.shape, tf.size(rank4_tensor)
2*2*4*5

80

In [28]:
print(f"Number of dimension previous tensor = {rank4_tensor.ndim}\nShape of tensor = {rank4_tensor.shape}\nSize of the tensor = {tf.size(rank4_tensor).numpy()}\
    \nElement along the 0 axis = {rank4_tensor.shape[0]}\nElement along the 5 axis = {rank4_tensor.shape[-1]}")

Number of dimension previous tensor = 4
Shape of tensor = (2, 2, 4, 5)
Size of the tensor = 80    
Element along the 0 axis = 2
Element along the 5 axis = 5


##### Slicing Tensor

In [30]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [34]:
# Get the first 2 element from tensor
rank4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [38]:
# Get the first elemet from tensor except for the final 1
rank4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [44]:
rank2_tensor = tf.constant([[3,4],[2,5]])
rank2_tensor, rank2_tensor.shape, rank2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 4],
        [2, 5]], dtype=int32)>,
 TensorShape([2, 2]),
 2)

In [46]:
# Get the last element from rank2 tensor
rank2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [48]:
# Add in extra dimension to tensor
rank3_tensor = rank2_tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[2],
        [5]]], dtype=int32)>

In [50]:
# Another way to do it
tf.expand_dims(rank2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[2],
        [5]]], dtype=int32)>

In [54]:
# Expand 0-axis
tf.expand_dims(rank2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 4],
        [2, 5]]], dtype=int32)>