##### Tensor Manipulation (tensor operations)
Basic Operation

" + - * / "

In [12]:
import tensorflow as tf

In [13]:
# Addition
tensor = tf.constant([[12, 4],[8, 15]])
tensor + 10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 14],
        [18, 25]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12,  4],
        [ 8, 15]], dtype=int32)>)

In [14]:
# Tensor saved addition
tensor1 = tensor + 10
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 14],
       [18, 25]], dtype=int32)>

In [15]:
# Subtraction
tensor2 = tensor - 2
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  2],
       [ 6, 13]], dtype=int32)>

In [16]:
# Multiplication
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24,  8],
       [16, 30]], dtype=int32)>

In [17]:
# Use build-in function
tensor3 = tf.multiply(tensor, 2)
tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24,  8],
       [16, 30]], dtype=int32)>

In [18]:
# Division
tensor4 = tensor / 2
tensor4

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[6. , 2. ],
       [4. , 7.5]])>

##### Matrix Multiplication

2 Rules of Matrix Multiplication:
1. The inner dimension must match
2. The resulting matrix has the shape of the inner dimension

In [19]:
# Matrix multiplication w/ build-in tf function
tensorA = tf.matmul(tensor1, tensor3)
tensorA

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[752, 596],
       [832, 894]], dtype=int32)>

In [20]:
# Matrix multiplication w/ python operator

tensorB = tensor2 @ tensor3
tensorB

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[272, 140],
       [352, 438]], dtype=int32)>

In [21]:
# Matrix multiplication problem
X = tf.constant([[4, 4],
                 [3, 5],
                 [1, 4]])
Y = tf.constant([[2, 4],
                 [1, 2],
                 [5, 5]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 4],
        [3, 5],
        [1, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [1, 2],
        [5, 5]], dtype=int32)>)

In [22]:
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Fixed problem

X_reshape = tf.reshape(X, shape=(-1, 3))
tf.matmul(Y, X_reshape)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[28, 12, 22],
       [14,  6, 11],
       [45, 25, 35]], dtype=int32)>

In [ ]:
# Transpose
tf.transpose(X_reshape)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [4, 1],
       [3, 4]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(Y), X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 33],
       [27, 46]], dtype=int32)>

Note

You can multiply matrix by using:
1. tf.matmul()
2. tf.tensordot()

##### Changing Datatype of a Tensor

In [ ]:
B = tf.constant([5, 7])
B.dtype

tf.int32

In [ ]:
C = tf.constant([3.14, 1.61])
C.dtype

tf.float32

In [ ]:
# Change int32/float32 to int16/float16 (reduced precision)

D = tf.cast(B, dtype=tf.int16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([5, 7], dtype=int16)>,
 tf.int16)

In [ ]:
E = tf.cast(C, dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.14, 1.61], dtype=float16)>

##### Tensor Aggregation

Aggregating Tensor = condensing tensor multiple values down to a smaller values

In [ ]:
# Get the absolute value
D = tf.constant([13, 12])

In [ ]:
# Get the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([13, 12], dtype=int32)>

Form of Aggregration

- Get the minimum
- Get the maximum
- Get the mean
- Get the sum

In [ ]:
# Tensor with a random value between 0 - 100 with the size of 50

import numpy as np
E = tf.constant(np.random.randint(0, 100, size=50))
E.shape, E.ndim, tf.size(E), E

(TensorShape([50]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([ 6, 15, 77,  8, 15, 31, 40, 54,  4, 66,  1, 10, 32, 77, 50, 83, 51,
        50, 26, 11, 80,  1,  4, 26, 14, 79, 90, 74, 44, 42, 37, 20, 12, 75,
        34, 57, 88, 61, 29, 82, 92, 90, 88, 42, 71, 20, 53, 97, 84, 83],
       dtype=int32)>)

In [ ]:
# Get the min val of tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
# Get the max val of tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [ ]:
# Get the mean of tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=47>

In [ ]:
# Get the sum of tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2376>

🛠️ Exercise: find the variance and standard deviation of E

In [ ]:
# Get variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=904.5>

In [ ]:
# Get standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=30.078125>

##### Find the Positional Max & Min Val

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find positional max val
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Get index positional max val
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
# Get the positional min val
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>